# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sub-Assert
version:      1.21
version_from: lib/Sub/Assert.pm
installdirs:  site
requires:
    Carp:                          0
    Exporter:                      0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
