--- #YAML:1.0
name:                Sub-Assert
version:             1.22
abstract:            Design-by-contract like pre- and postconditions, etc.
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Carp:                          0
    Exporter:                      0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Steffen Mueller <smueller@cpan.org>
